s3:
  download_file_from_s3:
    local_paths: ['data/raw/RAW_recipes.csv', 'data/raw/RAW_interactions.csv']
    s3paths: ['s3://2021-msia423-chen-zhiyang/raw_data/RAW_recipes.csv',
              's3://2021-msia423-chen-zhiyang/raw_data/RAW_interactions.csv']

clean:
  recipe_in_path: data/raw/RAW_recipes.csv
  prepare_recipe:
    prep_ingredient:
      ing_col: ingredients
      inglist: [ 'pepper', 'onion', 'cheese', 'garlic', 'egg', 'butter', 'flour', 'lemon', 'chicken', 'milk', 'tomato',
                 'cream', 'baking', 'vanilla', 'cinnamon', 'parsley', 'apple', 'beef', 'potato', 'chili']
      similarlist:
        lime: lemon
        cheddar: cheese
        mozzarella: cheese
    prep_tag:
      tag_col: tags
      taglist: ['dietary', 'easy', 'low-in-something', 'main-dish', 'meat', 'vegetables', 'north-american', 'desserts',
                'healthy', 'dinner-party', 'vegetarian', 'beginner-cook', 'inexpensive', 'fruit', 'oven', 'eggs-dairy',
                'pasta-rice-and-grains', 'kid-friendly', 'comfort-food', 'european']
    prep_nutrition:
      nutr_col: nutrition
      nutritionlist: ['calories', 'total_fat', 'sugar', 'sodium', 'protein', 'saturated_fat', 'carbs']
    step_col: 'steps'
    strlist: ['tags', 'ingredients']

  recipe_out_path: data/clean/recipes.csv
  get_recipe:
    droplist: ['contributor_id', 'submitted', 'tags', 'nutrition', 'description', 'ingredients', 'steps']

  rds_path: data/clean/rds.csv
  get_rds:
    collist: ['id', 'name', 'description', 'minutes', 'tags', 'calories', 'total_fat', 'sugar', 'sodium',
              'protein', 'saturated_fat', 'carbs','n_ingredients', 'ingredients', 'n_steps', 'steps']

  interaction_in_path: data/raw/RAW_interactions.csv
  interaction_out_path: data/clean/interactions.csv
  prepare_interactions:
    uid_col: user_id
    rid_col: recipe_id
    rating_col: rating
    list_col: list
    count_col: count
    top_n: 10

model:
  clean_data_path: data/clean/recipes.csv
  model_data_path: model/kmeans.pkl
  kmeans_model:
    droplist: ['id', 'name']
    clust_col: cluster
    n_cluster: 20
    seed: 423

  get_items:
    id_col: id
    name_col: name
    top_n: 10

evaluate:
  result_path: model/result.csv
  evaluation:
    clust_col: cluster
    list_col: list
    rating_col: rating
    rank_col: rank
    id_col: id
    top_n: 10
